CREATE TABLE IF NOT EXISTS `FoA_DA` (
  `DaId` INT NOT NULL AUTO_INCREMENT,
  `Titel` VARCHAR(100) NOT NULL,
  `Schueler` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`DaId`)
);

CREATE TABLE if NOT EXISTS `FoA_QrCodes`(
 `QrId` VARCHAR(8) NOT NULL, 
 PRIMARY KEY(`QrId`)
);
#id - bekomme paul VARCHAR


CREATE TABLE if NOT EXISTS `FoA_Vote`(
`VotingId`INT NOT NULL AUTO_INCREMENT,
`QrId` VARCHAR(8) NOT NULL, 
`DaId` INT NOT NULL, 
PRIMARY KEY (`VotingId`), 
FOREIGN KEY (`QrId`) REFERENCES FoA_QrCodes (`QrId`) ON DELETE CASCADE,
FOREIGN KEY (`DaId`) REFERENCES FoA_DA (`DaId`) ON DELETE CASCADE
);

#INSERT INTO FoA_DA
#VALUES (NULL, "Die 2 Neueste DA", "Hubert");

#INSERT INTO FoA_QrCodes
#VALUES ("Fq2974JK"); 

#INSERT INTO FoA_Vote
#VALUES (NULL, "Fq2974JK", 1);
