CREATE TABLE IF NOT EXISTS `FoA_DA` (
  `DaId` INT NOT NULL AUTO_INCREMENT,
  `Titel` VARCHAR(100) NOT NULL,
  `Schueler` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`DaId`)
);

CREATE TABLE if NOT EXISTS `FoA_QrCodes`(
 `QrId` VARCHAR(8) NOT NULL, 
 PRIMARY KEY(`QrId`)
);
#id - bekomme paul VARCHAR

CREATE TABLE IF NOT EXISTS foa_admin (
BenutzerId INT AUTO_INCREMENT, 
Benutzername VARCHAR(50) NOT NULL UNIQUE,
Passwort VARCHAR(255),
PRIMARY KEY(BenutzerId)
);

CREATE TABLE if NOT EXISTS `FoA_Voting`(
`VotingId`INT NOT NULL AUTO_INCREMENT,
`QrId` VARCHAR(8) NOT NULL UNIQUE, 
`Fav` INT,,
`DaOther1` INT, 
`DaOther2` INT,
`DaOther3` INT,
`DaOther4` INT,
`DaOther5` INT,
PRIMARY KEY (`VotingId`), 
FOREIGN KEY (`QrId`) REFERENCES FoA_QrCodes (`QrId`) ON DELETE CASCADE,
FOREIGN KEY (`Fav`) REFERENCES FoA_DA (`DaId`) ON DELETE CASCADE,
FOREIGN KEY (`DaOther1`) REFERENCES FoA_DA (`DaId`) ON DELETE CASCADE,
FOREIGN KEY (`DaOther2`) REFERENCES FoA_DA (`DaId`) ON DELETE CASCADE,
FOREIGN KEY (`DaOther3`) REFERENCES FoA_DA (`DaId`) ON DELETE CASCADE,
FOREIGN KEY (`DaOther4`) REFERENCES FoA_DA (`DaId`) ON DELETE CASCADE,
FOREIGN KEY (`DaOther5`) REFERENCES FoA_DA (`DaId`) ON DELETE CASCADE
);

#INSERT INTO FoA_DA
#VALUES (NULL, "Die 2 Neueste DA", "Hubert");

#INSERT INTO FoA_QrCodes
#VALUES ("Fq2974JK"); 

#INSERT INTO FoA_Voting_System
#VALUES (NULL, "Fq2974JK", 1);
